# Use postgres/example user/password credentials
version: '3.9'

services:
  app:
    build: .
    container_name: review-service-jakartaee
    ports:
      - "8181:8080"
    depends_on:
      - review-service-db

  review-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5434:5432"