# Use postgres/example user/password credentials
version: '3.9'

services:

  review-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5434:5432"