# Use postgres/example user/password credentials
version: '3.9'

services:
  app:
    build: .
    container_name: review-service-jakartaee
    ports:
      - "8181:8181"
    depends_on:
      - review-service-db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=your_database
      - DB_USER=your_user
      - DB_PASSWORD=your_password

  review-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5434:5432"