version: '3.1'

services:
  nodejs-app:
    build: .
    container_name: nodejs-app
    restart: unless-stopped
    ports:
      - '8383:8383'
    environment:
      PORT: 8383
      NODE_ENV: development
      MONGO_USER: root
      MONGO_PASS: example
      MONGO_PORT: 27018
      DB_NAME: sanadlite
      JWT_SECRET_KEY: sanadlite
      JWT_EXPIRES_IN: 90d
      BCRYPT_SALT: 8
      COURSE_SERVICE_PORT: 8080
      ENROLLMENT_SERVICE_PORT: 8282
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    hostname: 'localhost'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181